# -*- coding: utf-8 -*-
"""green destinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eClka02t5ESl6uZAyX7xktMzFWSNMSU3
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('greendestination (1).csv')

# Display the first few rows of the DataFrame to verify it loaded correctly
print(df.head())

# Get a summary of the DataFrame, including data types and non-null values
print(df.info())


# Calculate the attrition rate

# Attrition Rate=((Total Number of Employees)/(Number of Employees Who Left))*100

attrition_counts = df['Attrition'].value_counts()
total_employees = len(df)
attrition_yes = attrition_counts.get('Yes', 0) # Get count of 'Yes' for Attrition
attrition_rate = (attrition_yes / total_employees) * 100

print(f"Attrition Rate: {attrition_rate:.2f}%")


import matplotlib.pyplot as plt
import seaborn as sns

factors = ['Age', 'YearsAtCompany', 'MonthlyIncome']

for factor in factors:
    # Create a new figure for each plot
    plt.figure(figsize=(8, 6))

    # Generate a box plot
    sns.boxplot(x='Attrition', y=factor, data=df)

    # Set plot title and labels
    plt.title(f'{factor} vs. Attrition')
    plt.xlabel('Attrition')
    plt.ylabel(factor)

    # Save the plot as an image file
    plt.savefig(f'{factor}_vs_Attrition.png')

    # Close the plot to free up memory
    #plt.close()
